### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CMYKCJMY** [kaydensigh/chromecalclock#10]
Hi. I am not a programmer. I like that the program/chromecalclock has a checkbox for staying on top. As a simple user, I'm not sure what clicking the StayOnTop checkbox effects.

I assume the idea is that chromecalclock can be invoked, referred to, and then the user's attention moves to their next task and then chromecalclock is dropped. As a user, I desire a feature I might describe as a Reference checkbox, which causes chromecalclock to truly stay visual all the time, so that I can arrange browser windows in relation to chromecalclock geometrically, and be able to look at chromecalclock as a true reference tool for time zones, as I complete other tasks throughout the day.

Please forgive me if I speak out of place, but I appreciate the design of chromecalclock, and the elegant selection of time zones by continent and then city. This additional feature would make chromecalclock more useful to me, and perhaps to other people as well.

Thank you for your time.

CMYKCJMY

**Comment by kaydensigh** [comment]
I'm not sure if I fully understand your request here but there's a couple of things you should try:
- Uncheck "Hide automatically" in the settings. This prevents the app from closing if you click on a different window.
- Move the app around by clicking anywhere on the app and dragging it.
That might allow you to do most of what you want.

**Comment by CMYKCJMY** [comment]
Thank you.
