### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luop90** [kaydensigh/chromecalclock#11]
Not sure if this is possible, but I would like to have the calc-clock open when I click on the date in bottom right toolbar (similar to what occurs with windows.)

I haven't delved into any ChromeOS APIs, but is it possible to override what happens when the date is clicked on, so that rather than going to the date/time settings, this app opens up?

Thanks.

**Comment by kaydensigh** [comment]
Yeah, it would be great to have an API for persistent utilities to have a
small presence in the bottom right. Unfortunately I don't think this exists
at the moment.
