### ISSUE TITLE
Calender widget contracted to 6 colums (making the calender wrong)

### ISSUE THREAD

**Issue by felixhoornaert** [kaydensigh/chromecalclock#15]
![Screenshot 2019-09-11 at 21 11 39](https://user-images.githubusercontent.com/13853406/64684488-4f017c80-d4d9-11e9-8a4d-ea3d24bb45fe.png)

Since a while I have this problem with the application on my chromebook. It might have to do with the screen resolution, i have my resolution set to 0.85% of the screen resolution ( 1807x1016 instead of 1536x864, which is set as the default (wrongly I have the feeling?) ), and the problem disappears when I set the resolution to default.

Any chance there is a fix for this? Id happily donate you a large coffee for the fix, since I really love your widget :-)

**Comment by RudolfRendier** [comment]
Thanks for pointing out that this is a resolution issue. I zoomed out and the problem is gone.
Fine work around for me. A proper fix would be much appreciated.

**Comment by kaydensigh** [comment]
Also many comments from Chrome Web Store feedback with the same issue.

Probably a rounding issue with the size of the calendar widget.

**Comment by kaydensigh** [comment]
Should be fixed by 71774643256d7f2585e941fe916b22f5204ecd8b.
