### ISSUE TITLE
Saturday has gone down to the next row

### ISSUE THREAD

**Issue by Dianne0520** [kaydensigh/chromecalclock#22]
Hello, I love using this app, however, it is currently not giving me accurate data as the "Sat" has gone down below "Sun" where it should be just beside "Fri". As for the troubleshooting, I tried relaunching the app as well as uninstalling and reinstalling it back to no avail. Hope this gets fixed! :)
![Screenshot 2021-06-04 22 23 31](https://user-images.githubusercontent.com/85354957/120816718-98361180-c583-11eb-9830-540e32de3fb3.png)

**Comment by kaydensigh** [comment]
Thanks for filing this. It's a long standing issue (https://github.com/kaydensigh/chromecalclock/issues/15) that should be fixed by 71774643256d7f2585e941fe916b22f5204ecd8b.
