### ISSUE TITLE
Not working in in Windows XP.

### ISSUE THREAD

**Issue by Avinashachu007** [kaydensigh/chromecalclock#4]
I have downloaded this app from Chrome store. It is not working for me. 
I'm currently using Chrome Version 33.0.1750.117 & Windows XP service pack 3. I have attached my screen shot 
![image](https://cloud.githubusercontent.com/assets/12245421/8633414/e01cf074-27e4-11e5-963a-afa80c3029a2.png)

**Comment by kaydensigh** [comment]
Wow. I appreciate that you posted your Chrome and OS versions, but it's basically impossible to support such an old version of Chrome. Chrome is currently at 43. It normally auto-updates, so if this is your own PC (no enterprise policy), then it's likely you have malware that is preventing Chrome from updating. You could try uninstalling and reinstalling Chrome but, to be honest, the only long term solution is to upgrade to something newer than XP.

**Comment by Avinashachu007** [comment]
Great to see! I thought I wont get a reply for the comment. Thanks!! I'm using your 'chromecalclock' application in my office computer where enterprise policy is applied. I downloaded your application because there is no calender(also no clock) application in windows XP. **In Latest OS (including all modern OS such as linux,mac & even chrome OS),the clock and calender application is built right into the OS(probably in Task bar itself) .**So, there is no need of downloading this application. right? Also I cant install any windows software because it requires administrator privileges(Chrome apps doesn't require any privileges). so the primary audience  your application is the people having **old operating system**. Your app will get more audience if it supports old OS and Browsers.
*Note:Other latest chrome apps are working well on my Chrome browser*

**Comment by kaydensigh** [comment]
Ah I see. Yeah it's common for businesses to lock their version of Chrome for stability/compatibility reasons. Unfortunately, it's not practical to support all the versions of Chrome. Maybe you could convince your admins to upgrade to a newer version (it's a pretty big security hole to use an out-of-date browser).

In the mean time, if you could post the console output, I'll take a look and see if it's something trivial to fix. You can get to the console from chrome://extensions and clicking "main.html" under "Calendar Clock". Once the console window is open, restart the app, and copy any text that shows up.

**Comment by Avinashachu007** [comment]
:) no issues... Somehow I have updated my Chrome to version 43. Thank you :) :+1:
